### ISSUE TITLE
Docker install

### ISSUE THREAD

**Issue by lupa18** [DemocracyOS/democracyos#1376]
Hello, I'm trying to run docker image: https://hub.docker.com/r/democracyos/democracyos/ but something is not woking. 
Is there any extra documentation on how to use it ?

**Comment by gvilarino** [comment]
Please provide additional information as in your os, docker version, commands you're running and output

**Comment by lupa18** [comment]
I'm running: 
  Docker version 1.12.6, build 78d1802
  docker-compose version 1.11.2, build dfed245

I put it in a docker-compose file like this:

```
app:
  image: democracyos/democracyos
  restart: unless-stopped
  ports:
   - "80:3000"
```
But as I just said, I'm not sure how to use it, if I have to add some db or another parameters. 

thanks in advance!
